import os
print("this is my first time")

print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
print("this is my first time")
